import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/lib/db/client";
import { artifacts, type Artifact } from "@/lib/db/schema";

/**
 * Per-owner registry of artifacts generated by Poncho (image/audio/video/html).
 * Ephemeral holding pen — the owner promotes the keepers into the vault.
 */

export interface ArtifactInput {
  chatId?: string;
  kind: string; // image | audio | video | html
  url: string; // public URL for media; a synthetic key for html
  content?: string; // HTML markup (for kind "html")
  mimeType?: string;
  title?: string;
  description?: string;
}

export async function recordArtifacts(
  ownerId: string,
  items: ArtifactInput[]
): Promise<void> {
  if (!ownerId || items.length === 0) return;
  const db = getDb();
  const rows = items
    .filter((a) => a.url)
    .map((a) => ({
      ownerId,
      chatId: a.chatId ?? null,
      kind: a.kind || "image",
      url: a.url,
      content: a.content ?? null,
      mimeType: a.mimeType ?? null,
      title: a.title ?? null,
      description: a.description ?? null,
    }));
  if (rows.length === 0) return;
  // Dedupe on (owner, url) so re-polling the same run doesn't pile up copies.
  await db.insert(artifacts).values(rows).onConflictDoNothing();
}

export async function listArtifactsFor(ownerId: string): Promise<Artifact[]> {
  const db = getDb();
  return db
    .select()
    .from(artifacts)
    .where(eq(artifacts.ownerId, ownerId))
    .orderBy(desc(artifacts.createdAt))
    .limit(60);
}

export async function getArtifact(
  ownerId: string,
  id: string
): Promise<Artifact | null> {
  const db = getDb();
  const [row] = await db
    .select()
    .from(artifacts)
    .where(and(eq(artifacts.ownerId, ownerId), eq(artifacts.id, id)))
    .limit(1);
  return row ?? null;
}

export async function deleteArtifact(
  ownerId: string,
  id: string
): Promise<void> {
  const db = getDb();
  await db
    .delete(artifacts)
    .where(and(eq(artifacts.ownerId, ownerId), eq(artifacts.id, id)));
}
